# Analyzer config.
 
# Recommended lints.
include: package:flutter_lints/flutter.yaml

linter:
  # Lint rules.
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

# More info at dart.dev/guides/language/analysis-options.
