name: preppal
description: "A new Flutter project."
# Prevent publish.
publish_to: 'none' # Remove to publish

# Version and build.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies.
dependencies:
  flutter:
    sdk: flutter

  # iOS icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl: ^0.19.0 # Date format
  shared_preferences: ^2.2.3 # Local storage
  flutter_riverpod: ^2.5.1 # State management
  image_picker: ^1.0.7 # Image picker
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.1+16 # App check
  sqflite: any # SQLite
  path_provider: any # Path
  path: any # Path join
  connectivity_plus: any # Internet check
  confetti: ^0.7.0 # Confetti
  audioplayers: ^6.0.0 # Audio

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints.
  flutter_lints: ^5.0.0

# Pubspec info.

# Flutter specific.
flutter:

  # Material Icons.
  uses-material-design: true

  # Assets.
  assets:
    - assets/sounds/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Image variants.

  # Assets from packages.

  # Custom fonts.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Fonts from packages.
